version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lost_found_app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./.env:/var/www/html/.env
      - ./uploads:/var/www/html/uploads
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - lost_found_network

  db:
    image: mysql:8.0
    container_name: lost_found_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - lost_found_db_data:/var/lib/mysql
    networks:
      - lost_found_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lost_found_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - lost_found_network
    depends_on:
      - db

networks:
  lost_found_network:
    driver: bridge

volumes:
  lost_found_db_data: